### ISSUE TITLE
Invalid 'col': out of range -> When using CRLF and space (0x20) is following

### ISSUE THREAD

**Issue by Myzel394** [mcauley-penney/visual-whitespace.nvim#8] opened 2024-05-07 14:09 UTC
So I got this file where visual whitespace throws an error when going into visual mode.

I think the issue occurs when using CRLF encoded files and a space is following a newline immediately.

## Reproduction

1. Open a file
2. Enter some text, insert newline, immediately insert space and enter some more character
3. Enable :set fileformat=dos
4. Go to visual mode

Sample file in binary:

```
00000000 | 68 65 6c 6c 6f 0d 0a 20 | 77 6f 72 6c 64 0d 0a | hello__ |world__ 
```

## Error

```
Error detected while processing ModeChanged Autocommands for "*:[vV]":
Error executing lua callback: ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: Invalid 'col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: in function 'apply_marks'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:135: in function <...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:115>
```

**Comment by mcauley-penney** [comment] 2024-05-07 22:15
Thanks for the issue!

I am trying to recreate this right now and I can't find the issue. I am trying both the reproduction steps and with the sample file. Would you please provide more information?

**Comment by Myzel394** [comment] 2024-05-15 14:01
Hmm, I'm also not able to reproduce it anymore, I guess I just forgot to update.

**Comment by mcauley-penney** [comment] 2024-05-16 07:04
If it happens again, please let me know!

**Comment by arthurazs** [comment] 2024-06-14 14:33
Hi, just to let you know I'm getting the same error.

What I noticed is that the error is raised when I'm using a file in linux that was created on windows.

I duplicated the contents of a windows-created file, to a linux-created file. The error is risen only in the windows one.

See the `file` output bellow, fake is the windows one, fake2 is the linux one.

```bash
$ file -bi fake.py fake2.py
text/x-script.python; charset=us-ascii
text/x-script.python; charset=us-ascii

$ file -b fake.py fake2.py
Python script, ASCII text executable, with CRLF line terminators
Python script, ASCII text executable
```

**Comment by mcauley-penney** [comment] 2024-06-14 19:05
> What I noticed is that the error is raised when I'm using a file in linux that was created on windows.

This is very useful information and it immediately points me towards the problem. I'll look into this today and try have a solution before the end of my day

**Comment by mcauley-penney** [comment] 2024-06-18 14:55
> I duplicated the contents of a windows-created file, to a linux-created file. The error is risen only in the windows one.

@arthurazs Can you please give these two files, if you still have them? I'm still having trouble duplicating this and I would like a reproducible way to get the error.

**Comment by arthurazs** [comment] 2024-06-18 14:58
I'll try to remove some sensitive information from the files and share them with you.

I'm going to lunch right now, once I'm back (in a hour maybe) I'll share them with you!

**Comment by mcauley-penney** [comment] 2024-06-18 14:59
No worries, thank you for your help! Even other files that generate this error would be fine. I can't seem to reproduce whatever quality these files have that are giving off the problem, so any two files that do this are fine with me.

**Comment by arthurazs** [comment] 2024-06-18 15:03
I assume the issue has to do with windows using CRLF while linux uses only LF for line breaks.

[Reference](https://developer.mozilla.org/en-US/docs/Glossary/CRLF)

I'll send the files in a hour

**Comment by mcauley-penney** [comment] 2024-06-18 15:07
I'm very familiar with this, and the source code has provisions for changing what newline characters are detected based on the `fileformat`, but I can't seem to get an error thrown when using DOS files with CRLF endings on my Linux machine.

**Comment by arthurazs** [comment] 2024-06-18 16:14
Some how I cannot replicate the error anymore. Right now I'm using a Ubuntu machine.

Later tonight I'll get back to my own pc (which has Debian) and see if I can replicate the error again.

**Comment by mcauley-penney** [comment] 2024-06-18 17:13
No worries! This issue seems sneaky

**Comment by arthurazs** [comment] 2024-06-18 23:16
Hi, i forked the repo to upload the files.

[linux.py](https://github.com/arthurazs/visual-whitespace.nvim/blob/main/linux.py) and [windows.py](https://github.com/arthurazs/visual-whitespace.nvim/blob/main/windows.py).

Again, I could not replicate the error on my Ubuntu machine. Right now I'm using a Debian machine, and the error is present.

In the linux file, the selection works as intended:

![image](https://github.com/mcauley-penney/visual-whitespace.nvim/assets/3771055/f67eefc5-aa7c-4c0b-ade3-723036ba987c)

In the windows file, the error is risen:

![image](https://github.com/mcauley-penney/visual-whitespace.nvim/assets/3771055/05877d7b-6abb-447e-8c14-384a56a5227c)

I'll try to run this example in my Ubuntu tomorrow to see what happens.

---

Some more info:

I cloned the fork I created and the error persists. So I assume the files kept the characteristics to replicate the bug.

The machine is running Debian GNU/Linux 12 (bookworm).

I don't think this could be the issue, but right now this Debian Machine is running on a Oracle VM VirtualBox (version 7.0.10 r158379 - Qt5.15.2).
My host machine is a Windows 11 Home Single Language, and I'm connecting to the Debian machine using SSH. My terminal emulator is Alacritty (version 0.13.1 - fe2a3c5).

Here is the traceback:

```
Error executing vim.schedule lua callback: ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: Invalid 'col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: in function 'apply_marks'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:135: in function <...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:115>
```

Here is my vim version:

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Here is my checkhealth:

```
==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /tmp/.mount_vim7OBLBQ/usr/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $SSH_TTY="/dev/pts/0"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.6.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.0-21-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)"
} ~

Parser/Features         H L F I J
  - bash                âœ“ âœ“ âœ“ . âœ“
  - bibtex              âœ“ . âœ“ âœ“ .
  - c                   âœ“ âœ“ âœ“ âœ“ âœ“
  - fish                âœ“ âœ“ âœ“ âœ“ âœ“
  - gitignore           âœ“ . . . .
  - html                âœ“ âœ“ âœ“ âœ“ âœ“
  - lua                 âœ“ âœ“ âœ“ âœ“ âœ“
  - make                âœ“ . âœ“ . âœ“
  - markdown            âœ“ . âœ“ âœ“ âœ“
  - python              âœ“ âœ“ âœ“ âœ“ âœ“
  - query               âœ“ âœ“ âœ“ âœ“ âœ“
  - toml                âœ“ âœ“ âœ“ âœ“ âœ“
  - vim                 âœ“ âœ“ âœ“ . âœ“
  - vimdoc              âœ“ . . . âœ“
  - yaml                âœ“ âœ“ âœ“ âœ“ âœ“

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- WARNING No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
  - ADVICE:
    - :help |clipboard|

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "~/.config/nvim/.venv/bin/python"
- Executable: /home/me/.config/nvim/.venv/bin/python
- Python version: 3.11.2
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- WARNING `ruby` and `gem` must be in $PATH.
  - ADVICE:
    - Install Ruby and verify that `ruby` and `gem` commands work.

Node.js provider (optional) ~
- Node.js: v21.6.2
- Nvim node.js host: /home/me/.local/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 5.1.0

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/me/.local/state/nvim/lsp.log
- Log size: 2313 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: bibtex     ABI: 13, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/bibtex.so
- OK Parser: c          ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: fish       ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/fish.so
- OK Parser: gitignore  ABI: 13, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/gitignore.so
- OK Parser: html       ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: lua        ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: make       ABI: 13, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/make.so
- OK Parser: markdown   ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: python     ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: toml       ABI: 13, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so
- OK Parser: vim        ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml       ABI: 14, path: /home/me/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: c          ABI: 14, path: /tmp/.mount_vim7OBLBQ/usr/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /tmp/.mount_vim7OBLBQ/usr/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /tmp/.mount_vim7OBLBQ/usr/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /tmp/.mount_vim7OBLBQ/usr/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /tmp/.mount_vim7OBLBQ/usr/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gb"**
- rhs: `<Plug>(comment_toggle_blockwise)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: `<Plug>(comment_toggle_linewise)`
```

**Comment by mcauley-penney** [comment] 2024-06-19 02:53
Okay, so, I've tried a couple things and still can't reproduce it as of right now. The Windows file works on my Linux machine. 

I have confirmed that the `fileformat` is `dos`. I'm trying to reproduce it on Neovim 0.9.5. I've tried Alacritty. Based on the screenshot, it seems like it doesn't like the position I'm giving it for the linefeed char. It *seems* like the error appears when you attempt to select to the end of the line then move down one line, which is the only way to highlight the linefeed character in DOS files at the moment *when using charwise visual mode.

@arthurazs If its okay with you, I'd like you to try something for me. In the plugin source code on your machine (`~/.local/share/nvim` on my Linux machine), please go to [this line](https://github.com/arthurazs/visual-whitespace.nvim/blob/50758e983ac41a9eb9cbcce93ffa1630a332b580/lua/visual-whitespace.lua#L96) and change the 0 to a 1. Please save, then attempt to visually select the content in the Windows file again.

**Comment by arthurazs** [comment] 2024-06-19 13:18
> It _seems_ like the error appears when you attempt to select to the end of the line then move down one line

I think you are correct. IIRC I was using visual line mode (shift-v, to select the whole line). I'm not sure if the error was happening after or before I pressed down.

I'm using another Ubuntu machine right now, and the error is not present (this bug is really sneaky haha).
Once I get back home, I'll try the change you proposed and let you know the results!

**Comment by arthurazs** [comment] 2024-06-20 00:29
@mcauley-penney first of all, I want to thank you for all the help.

After following your latest suggestion, I discovered that my plugin was outdated. Once I updated it, the issue was resolved.

I apologize for my lack of attention due to the outdated plugin. I think you may close this issue again.

Thank you once again for your help!

**Comment by mcauley-penney** [comment] 2024-06-20 00:51
@arthurazs No worries at all, you have nothing to apologize about! I was happy to help. This ultimately gives me more information to work off of if anyone else happens to run into this problem in the future.

**Closed as completed by mcauley-penney** 2024-06-20 00:51 UTC
