### ISSUE TITLE
[bug]: wrong background highlight

### ISSUE THREAD

**Issue by luiz00martins** [mcauley-penney/visual-whitespace.nvim#3] opened 2024-03-13 07:04 UTC
## Description
The background on whitespaces keeps the highlight of the default background color, instead of the visual selection highlight.

## Screenshots

https://github.com/mcauley-penney/visual-whitespace.nvim/assets/43142209/905aa849-5a94-44e3-8006-0838358906bc

## Info
- Windows 10 19045.4046
- Windows Terminal 1.19.10573.0
- NVIM v0.10.0-dev-ee276f8
- visual-whitespace commit: 100c308

**Comment by luiz00martins** [comment] 2024-03-13 07:07
Note: May be fixed on user-side by using:
```
opts = {
  highlight = { link = 'Visual' },
},
```

**Comment by mcauley-penney** [comment] 2024-03-13 12:07
~~TLDR: linking to "Visual" won't work for color schemes that don't give "Visual" a foreground.~~

~~This is *not* a bug and doesn't require a fix. This is more akin to a feature request because it wants the plugin to automatically create the highlighting that you want. As you pointed out, there is a configuration option provided for the user to set their own highlights. To solve this in the way you expect, I'd have to include functionality that gets the Visual group background and sets a custom foreground. This is trivial to do, but is kind of out of scope and unnecessary when the user can do this themselves.~~

~~I made this change on purpose after another user noticed that they could not see the whitespace characters using the default link to "Visual". This happened because some color schemes do net set a foreground color for that highlight group, meaning the extmarks used to display the whitespace characters will not show up at all. So, the code you gave above is exactly what I was doing that created this problem in the first place and is *not* a solution because, to reiterate, it incorrectly assumes that users are using a color scheme that sets a Visual foreground.~~

I was wrong and spoke from an uninformed place. Linking to Visual does work. I've eaten my words, you were right.

**Closed as completed** 2024-03-14 16:11 UTC

**Comment by YodaEmbedding** [comment] 2024-12-10 21:53
I want to link to Visual for the same `guibg`, but it displays as if `guibg=NONE` when `guifg` is also used.

```vim
hi VisualNonText guifg=#5D5F71
hi link VisualNonText Visual
```

**Comment by mcauley-penney** [comment] 2024-12-10 22:49
@YodaEmbedding More explanation would be useful, because my understanding of linking hl groups is that the link overrides whatever was set before, which is to say that this *appears* to be the expected behavior for all of Neovim, not just the plugin.

**Comment by YodaEmbedding** [comment] 2025-04-01 08:03
The following doesn't work (obviously):

```vim
hi VisualNonText guifg=#5D5F71 guibg=Visual.guibg
```

So I wrote:

```lua
  config = function(_, opts)
    require("visual-whitespace").setup(opts)

    local default_fg = "#5d5f71"

    local on_colorscheme_change = function()
      local visual_hl = vim.api.nvim_get_hl(0, { name = "Visual" })
      vim.api.nvim_set_hl(0, "VisualNonText", {
        fg = default_fg,
        bg = visual_hl and visual_hl.bg,
      })
    end

    vim.api.nvim_create_autocmd("ColorScheme", {
      pattern = "*",
      callback = on_colorscheme_change,
    })

    on_colorscheme_change()
  end,
```

The above automatically changes `VisualNonText`'s background to match `Visual`, even if the colorscheme changes.
